import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f6f8',
  },

  authContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
    backgroundColor: '#f5f6f8',
  },
  authBox: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: 'white',
    borderRadius: 14,
    padding: 28,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  authTitle: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#111827',
    textAlign: 'center',
    marginBottom: 8,
  },
  authSubtitle: {
    fontSize: 15,
    color: '#6b7280',
    textAlign: 'center',
    marginBottom: 24,
  },
  input: {
    backgroundColor: '#fafafa',
    borderRadius: 8,
    padding: 12,
    fontSize: 15,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#d1d5db',
  },
  authButton: {
    backgroundColor: '#111827',
    borderRadius: 8,
    padding: 13,
    alignItems: 'center',
    marginTop: 8,
  },
  authButtonDisabled: {
    backgroundColor: '#9ca3af',
  },
  authButtonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '600',
  },
  switchText: {
    color: '#374151',
    textAlign: 'center',
    marginTop: 18,
    fontSize: 13,
  },
  authStatusBox: {
    marginTop: 12,
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderWidth: 1,
    backgroundColor: '#f4f8ff',
    borderColor: '#bcd3f2',
  },
  authStatusSuccess: {
    backgroundColor: '#eaf9ef',
    borderColor: '#8ec79e',
  },
  authStatusError: {
    backgroundColor: '#feeceb',
    borderColor: '#e2a5a2',
  },
  authStatusInfo: {
    backgroundColor: '#eef4ff',
    borderColor: '#9eb7e6',
  },
  authStatusText: {
    fontSize: 12,
    color: '#1f2937',
  },
  authModernContainer: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 28,
    backgroundColor: 'transparent',
    alignItems: 'center',
  },
  authScreenContainer: {
    position: 'relative',
    backgroundColor: '#ffffff',
  },
  authBackgroundGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  authTopBar: {
    width: '100%',
    maxWidth: 480,
    height: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  authBackButton: {
    width: 44,
    height: 44,
    borderRadius: 99,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#dce0e5',
  },
  authBackButtonGhost: {
    opacity: 0.12,
  },
  authBackIcon: {
    fontSize: 20,
    color: '#111418',
    fontWeight: '700',
  },
  authTopTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#111418',
  },
  authTopRightSpace: {
    width: 44,
    height: 44,
  },
  authHeroWrap: {
    width: '100%',
    maxWidth: 480,
    marginTop: 4,
  },
  authHeroImage: {
    width: '100%',
    height: 188,
    justifyContent: 'flex-end',
    overflow: 'hidden',
  },
  authHeroImageSignIn: {
    height: 210,
  },
  authHeroImageRadius: {
    borderRadius: 14,
  },
  authHeroOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(19, 127, 236, 0.14)',
  },
  authHeadingBlock: {
    width: '100%',
    maxWidth: 480,
    paddingTop: 16,
    paddingBottom: 6,
    alignItems: 'center',
  },
  authHeading: {
    fontSize: 34,
    fontWeight: '900',
    color: '#111418',
    textAlign: 'center',
    letterSpacing: -0.7,
  },
  authBodyText: {
    marginTop: 8,
    fontSize: 15,
    lineHeight: 22,
    color: '#637588',
    textAlign: 'center',
    maxWidth: 420,
  },
  authFormBlock: {
    width: '100%',
    maxWidth: 480,
    paddingTop: 10,
    gap: 12,
  },
  authField: {
    gap: 7,
  },
  authFieldLabel: {
    fontSize: 15,
    fontWeight: '700',
    color: '#111418',
  },
  authInputShell: {
    height: 56,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#dce0e5',
    backgroundColor: '#f0f2f4',
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 14,
    paddingRight: 12,
  },
  authInputControl: {
    flex: 1,
    height: '100%',
    fontSize: 16,
    color: '#111418',
    backgroundColor: 'transparent',
    borderWidth: 0,
    padding: 0,
    margin: 0,
  },
  authInputControlWeb: {
    outlineStyle: 'none',
    outlineWidth: 0,
    outlineColor: 'transparent',
    boxShadow: 'none',
  },
  authInputIconWrap: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  authInputIcon: {
    marginLeft: 10,
    fontSize: 19,
    color: '#637588',
  },
  authActionArea: {
    width: '100%',
    maxWidth: 480,
    paddingTop: 16,
  },
  authPrimaryButton: {
    height: 56,
    borderRadius: 12,
    backgroundColor: '#137fec',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#137fec',
    shadowOpacity: 0.28,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 4,
  },
  authPrimaryButtonDisabled: {
    opacity: 0.65,
  },
  authPrimaryButtonInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  authPrimaryButtonText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '800',
  },
  authPrimaryButtonIcon: {
    color: '#ffffff',
    fontSize: 16,
  },
  authFooterArea: {
    width: '100%',
    maxWidth: 480,
    paddingTop: 18,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  authFooterText: {
    color: '#637588',
    fontSize: 15,
  },
  authFooterLink: {
    color: '#137fec',
    fontSize: 15,
    fontWeight: '800',
  },

  homeHeader: {
    backgroundColor: '#ffffff',
    width: '100%',
    maxWidth: 1100,
    alignSelf: 'center',
    marginTop: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#d6deeb',
    paddingHorizontal: 20,
    paddingVertical: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#0f172a',
    shadowOpacity: 0.08,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
  },
  homeScreen: {
    backgroundColor: '#e7edf6',
  },
  homeTitle: {
    color: '#081635',
    fontSize: 40,
    fontWeight: '800',
    letterSpacing: -0.6,
  },
  homeSubtitle: {
    color: '#506079',
    fontSize: 14,
    marginTop: 4,
    fontWeight: '600',
  },
  homeHeaderActions: {
    flexDirection: 'row',
    gap: 10,
  },
  secondaryButton: {
    backgroundColor: '#f8fbff',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#c8d4e7',
  },
  secondaryButtonText: {
    color: '#0f1c3e',
    fontWeight: '700',
    fontSize: 13,
  },
  logoutButton: {
    backgroundColor: '#fff7f7',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#f8b7b7',
  },
  logoutButtonText: {
    color: '#b91c1c',
    fontWeight: '800',
    fontSize: 13,
  },
  homeContent: {
    width: '100%',
    maxWidth: 1100,
    alignSelf: 'center',
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 22,
    gap: 14,
  },
  createCard: {
    backgroundColor: 'white',
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: '#d6deeb',
    shadowColor: '#0f172a',
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 1,
  },
  cardTitle: {
    fontSize: 21,
    fontWeight: '800',
    color: '#081635',
    marginBottom: 10,
    letterSpacing: -0.2,
  },
  helperText: {
    fontSize: 13,
    color: '#5d6d85',
    marginBottom: 10,
    lineHeight: 18,
  },
  createForm: {
    flexDirection: 'column',
    gap: 12,
    alignItems: 'stretch',
  },
  createInput: {
    width: '100%',
    marginBottom: 0,
  },
  homeInput: {
    height: 56,
    borderRadius: 12,
    borderColor: '#cad6e8',
    backgroundColor: '#f8fbff',
    fontSize: 16,
    color: '#0f1c3e',
    paddingHorizontal: 14,
    paddingVertical: 0,
  },
  homeInputWeb: {
    outlineStyle: 'none',
    outlineWidth: 0,
    outlineColor: 'transparent',
    boxShadow: 'none',
  },
  homePrimaryButton: {
    height: 50,
    borderRadius: 12,
    backgroundColor: '#0d1730',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0d1730',
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  homePrimaryButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
  },
  createButton: {
    marginTop: 0,
    paddingHorizontal: 22,
    alignSelf: 'flex-end',
  },
  projectListCard: {
    backgroundColor: 'white',
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: '#d6deeb',
    shadowColor: '#0f172a',
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 1,
  },
  recentProjectsCard: {
    minHeight: 280,
  },
  projectList: {
    gap: 10,
    paddingBottom: 8,
  },
  projectItem: {
    borderWidth: 1,
    borderColor: '#d8e1ee',
    borderRadius: 12,
    padding: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#f8fbff',
  },
  projectInfo: {
    flex: 1,
    paddingRight: 10,
  },
  projectName: {
    fontSize: 20,
    fontWeight: '800',
    color: '#0c1937',
  },
  projectMeta: {
    fontSize: 13,
    color: '#53657f',
    marginTop: 6,
  },
  projectActions: {
    gap: 10,
    alignItems: 'flex-end',
  },
  openButton: {
    backgroundColor: '#0d1730',
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  openButtonText: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 13,
  },
  deleteButton: {
    backgroundColor: '#fff7f7',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#f8b7b7',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  deleteButtonText: {
    color: '#b91c1c',
    fontWeight: '800',
    fontSize: 12,
  },
  emptyText: {
    fontSize: 14,
    color: '#5d6d85',
    paddingVertical: 12,
  },

  toolbar: {
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    paddingVertical: 10,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
  },
  toolbarSection: {
    marginHorizontal: 4,
    marginBottom: 6,
  },
  sectionLabel: {
    fontSize: 10,
    color: '#6b7280',
    marginBottom: 6,
    fontWeight: '600',
  },
  projectTag: {
    maxWidth: 130,
    fontSize: 12,
    color: '#111827',
    fontWeight: '700',
    marginBottom: 4,
  },
  projectInviteCode: {
    maxWidth: 180,
    fontSize: 10,
    color: '#475569',
    fontWeight: '600',
    marginBottom: 6,
  },
  sessionActions: {
    gap: 4,
  },
  sessionButton: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 6,
    minWidth: 70,
  },
  sessionButtonText: {
    fontSize: 11,
    color: '#334155',
    fontWeight: '700',
    textAlign: 'center',
  },
  divider: {
    width: 1,
    backgroundColor: '#e5e7eb',
    alignSelf: 'stretch',
    marginHorizontal: 4,
  },
  toolsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: 88,
  },
  shapesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: 132,
  },
  toolButton: {
    width: 40,
    height: 40,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 3,
    alignItems: 'center',
    justifyContent: 'center',
    margin: 1,
  },
  toolButtonActive: {
    backgroundColor: '#f3f4f6',
    borderColor: '#111827',
    borderWidth: 2,
  },
  toolIcon: {
    fontSize: 18,
  },
  brushPanel: {
    width: 190,
    gap: 6,
  },
  brushSliderWrap: {
    gap: 5,
  },
  brushSliderHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  brushSliderValue: {
    fontSize: 11,
    color: '#0f172a',
    fontWeight: '700',
  },
  brushSliderHint: {
    fontSize: 10,
    color: '#64748b',
    fontWeight: '600',
  },
  brushSliderTrack: {
    height: 18,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    backgroundColor: '#f8fafc',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  brushSliderFill: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: '#bfdbfe',
  },
  brushSliderThumb: {
    position: 'absolute',
    width: 16,
    height: 16,
    borderRadius: 99,
    backgroundColor: '#2563eb',
    borderWidth: 2,
    borderColor: '#ffffff',
    top: 1,
  },
  brushesGrid: {
    flexDirection: 'row',
    gap: 3,
    flexWrap: 'wrap',
  },
  brushButton: {
    width: 35,
    height: 35,
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brushButtonActive: {
    backgroundColor: '#f3f4f6',
    borderColor: '#111827',
    borderWidth: 2,
  },
  brushDot: {
    backgroundColor: '#000',
    borderRadius: 50,
  },
  colorsContainer: {
    flexDirection: 'row',
    gap: 8,
  },
  colorsSectionWrap: {
    gap: 8,
  },
  colorsPalette: {
    gap: 1,
  },
  colorRow: {
    flexDirection: 'row',
    gap: 1,
  },
  colorButton: {
    width: 22,
    height: 22,
    borderWidth: 1,
    borderColor: '#888',
  },
  colorButtonActive: {
    borderWidth: 2,
    borderColor: '#111827',
    transform: [{ scale: 1.1 }],
  },
  currentColorContainer: {
    justifyContent: 'flex-end',
  },
  currentColorBox: {
    width: 50,
    height: 50,
    borderWidth: 2,
    borderColor: '#888',
    borderRadius: 3,
  },
  rgbaPanel: {
    width: 258,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 10,
    gap: 8,
  },
  rgbaPanelHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  rgbaPanelTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#111827',
  },
  rgbaCloseText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#475569',
  },
  rgbaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  rgbaLabel: {
    width: 14,
    fontSize: 11,
    fontWeight: '700',
    color: '#334155',
  },
  rgbaTrack: {
    flex: 1,
    height: 12,
    borderRadius: 99,
    backgroundColor: '#eef2f7',
    borderWidth: 1,
    borderColor: '#d1d5db',
    overflow: 'hidden',
    justifyContent: 'center',
  },
  rgbaFill: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
  },
  rgbaThumb: {
    position: 'absolute',
    width: 14,
    height: 14,
    borderRadius: 99,
    backgroundColor: '#ffffff',
    borderWidth: 2,
    top: -1,
  },
  rgbaValue: {
    width: 36,
    textAlign: 'right',
    fontSize: 11,
    color: '#475569',
    fontWeight: '600',
  },
  rgbaCodeText: {
    marginTop: 2,
    fontSize: 11,
    color: '#111827',
    fontWeight: '600',
  },
  actionsGrid: {
    flexDirection: 'row',
    gap: 3,
  },
  actionButton: {
    width: 35,
    height: 35,
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: '#d1d1d1',
    borderRadius: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionIcon: {
    fontSize: 18,
  },
  clearButton: {
    paddingHorizontal: 12,
    height: 35,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#fecaca',
    borderRadius: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  clearButtonText: {
    color: '#d32f2f',
    fontSize: 12,
    fontWeight: '600',
  },
  actionButtonDisabled: {
    opacity: 0.3,
  },
  actionIconDisabled: {
    opacity: 0.5,
  },
  workspace: {
    flex: 1,
    flexDirection: 'row',
  },
  canvasContainer: {
    flex: 1,
    backgroundColor: '#ffffff',
    margin: 12,
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 10,
    overflow: 'hidden',
  },
  canvasContainerWithSidePanel: {
    marginRight: 0,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
  },
  svg: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  textSidePanel: {
    width: 300,
    backgroundColor: '#f3f4f6',
    borderLeftWidth: 1,
    borderLeftColor: '#d1d5db',
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 10,
    marginTop: 12,
    marginRight: 12,
    marginBottom: 12,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
  },
  textSidePanelTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 6,
  },
  textSideLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#374151',
  },
  textSideSelect: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 9,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  textSideSelectText: {
    fontSize: 13,
    color: '#111827',
  },
  textSideSelectCaret: {
    fontSize: 12,
    color: '#64748b',
  },
  textSideControlRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  textSideControlLabel: {
    width: 36,
    fontSize: 12,
    color: '#475569',
    fontWeight: '600',
  },
  textSideMiniButton: {
    width: 26,
    height: 26,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textSideMiniButtonText: {
    fontSize: 14,
    color: '#111827',
    fontWeight: '700',
  },
  textSideValue: {
    minWidth: 56,
    textAlign: 'center',
    fontSize: 12,
    fontWeight: '600',
    color: '#111827',
  },
  textStyleRow: {
    flexDirection: 'row',
    gap: 8,
  },
  textStyleButton: {
    width: 34,
    height: 34,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  textStyleButtonActive: {
    borderColor: '#38bdf8',
    backgroundColor: '#e0f2fe',
  },
  textStyleButtonText: {
    color: '#111827',
    fontWeight: '700',
    fontSize: 16,
  },
  textStyleItalic: {
    fontStyle: 'italic',
  },
  textStyleUnderline: {
    textDecorationLine: 'underline',
  },
  textAlignRow: {
    flexDirection: 'row',
    gap: 8,
  },
  textAlignButton: {
    minWidth: 42,
    height: 32,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  textAlignButtonActive: {
    borderColor: '#38bdf8',
    backgroundColor: '#e0f2fe',
  },
  textAlignButtonText: {
    color: '#111827',
    fontWeight: '700',
    fontSize: 12,
  },
  textColorRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  textColorSwatch: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#cbd5e1',
  },
  textColorSwatchActive: {
    borderColor: '#0ea5e9',
    borderWidth: 2,
  },
  textSideCheckbox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  textSideCheckboxSquare: {
    width: 16,
    height: 16,
    borderRadius: 3,
    borderWidth: 1,
    borderColor: '#94a3b8',
    backgroundColor: '#ffffff',
  },
  textSideCheckboxSquareChecked: {
    backgroundColor: '#0ea5e9',
    borderColor: '#0ea5e9',
  },
  textSideCheckboxLabel: {
    fontSize: 13,
    color: '#334155',
    fontWeight: '600',
  },
  textSideInput: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 13,
    color: '#111827',
  },
  textSideInputReady: {
    borderColor: '#38bdf8',
    borderWidth: 2,
  },
  textCanvasEditor: {
    position: 'absolute',
    borderWidth: 1.4,
    borderColor: '#38bdf8',
    borderStyle: 'dashed',
    backgroundColor: 'rgba(255,255,255,0.96)',
    paddingHorizontal: 8,
    paddingVertical: 6,
    justifyContent: 'flex-start',
  },
  textCanvasInput: {
    width: '100%',
    color: '#111827',
    padding: 0,
    margin: 0,
  },
  textCanvasHandleLayer: {
    ...StyleSheet.absoluteFillObject,
    pointerEvents: 'none',
  },
  textCanvasHandle: {
    position: 'absolute',
    width: 8,
    height: 8,
    borderRadius: 99,
    borderWidth: 1,
    borderColor: '#ffffff',
    backgroundColor: '#38bdf8',
  },
  statusBar: {
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    paddingHorizontal: 12,
    paddingVertical: 6,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  statusLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
    flex: 1,
  },
  statusText: {
    color: '#374151',
    fontSize: 11,
    fontWeight: '500',
  },
  statusDivider: {
    color: '#9ca3af',
    fontSize: 11,
  },
  statusRight: {
    color: '#111827',
    fontSize: 11,
    fontWeight: '600',
  },
});
